### ISSUE TITLE
*** TypeError: __init__() got an unexpected keyword argument 'rgb_feats_dir_path'

### ISSUE THREAD

**Issue by YingqingHe** [v-iashin/SpecVQGAN#34]
When I run the evaluation commands, 
```
# Sample
EXPERIMENT_PATH="logs/2021-05-19T22-16-54_vggsound_codebook"
SPEC_DIR_PATH="./data/vas/features/*/melspec_10s_22050hz/"
RGB_FEATS_DIR_PATH="./data/vas/features/*/feature_rgb_bninception_dim1024_21.5fps/"
FLOW_FEATS_DIR_PATH="./data/vas/features/*/feature_flow_bninception_dim1024_21.5fps/"
SAMPLES_FOLDER="VAS_validation"
# SPLITS="\"[validation, ]\""
SPLITS="validation,"
SAMPLER_BATCHSIZE=1 #4
SAMPLES_PER_VIDEO=1 #10
TOP_K=64 # use TOP_K=512 when evaluating a VAS transformer trained with a VGGSound codebook
NOW=`date +"%Y-%m-%dT%H-%M-%S"`


python -m torch.distributed.launch \
    --nproc_per_node=3 \
    --nnodes=1 \
    --node_rank=0 \
    --master_addr=localhost \
    --master_port=62374 \
    --use_env \
        evaluation/generate_samples.py \
        sampler.config_sampler=evaluation/configs/sampler.yaml \
        sampler.model_logdir=$EXPERIMENT_PATH \
        sampler.splits=$SPLITS \
        sampler.samples_per_video=$SAMPLES_PER_VIDEO \
        sampler.batch_size=$SAMPLER_BATCHSIZE \
        sampler.top_k=$TOP_K \
        data.params.spec_dir_path=$SPEC_DIR_PATH \
        data.params.rgb_feats_dir_path=$RGB_FEATS_DIR_PATH \
        data.params.flow_feats_dir_path=$FLOW_FEATS_DIR_PATH \
        sampler.now=$NOW
```

I meet this bug:
```
*** TypeError: __init__() got an unexpected keyword argument 'rgb_feats_dir_path'
```

I am wondering how to fix this bug?

**Comment by v-iashin** [comment]
It means that your dataset class (`cfg.data.params.train.target`) does not have this argument in the `__init__` call. 

Could you check that?

**Comment by YingqingHe** [comment]
Thanks for your very prompt reply! Yes it is the reason. I load the config in the downloaded ckpt log folder, which is `logs/2021-05-19T22-16-54_vggsound_codebook/configs/2021-05-19T22-16-54-project.yaml`. The data config is: 
```
data:
  target: train.SpectrogramDataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    spec_dir_path: /run/nvme/job_559260/data/melspec_10s_22050hz/
    sample_rate: 22050
    mel_num: 80
    spec_len: 860
    spec_crop_len: 848
    random_crop: false
    train:
      target: specvqgan.data.vggsound.VGGSoundSpecsTrain
      params:
        specs_dataset_cfg: null
    validation:
      target: specvqgan.data.vggsound.VGGSoundSpecsValidation
      params:
        specs_dataset_cfg: null
    test:
      target: specvqgan.data.vggsound.VGGSoundSpecsTest
      params:
        specs_dataset_cfg: null
```
However, in the`SpectrogramDataModuleFromConfig` class, there is no `rgb_feats_dir_path` argument. 
When I change the data class from `target: train.SpectrogramDataModuleFromConfig` to `target: train.ConditionedSpectrogramDataModuleFromConfig`, this bug solved. However, when running to `dsets.prepare_data()` at https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/evaluation/generate_samples.py#L88C5-L88C25, it raise another error:
```
*** TypeError: __init__() got an unexpected keyword argument 'condition_dataset_cfg'
```
Do you have any suggestions for this issue? Many thanks~
